#nom du pipeline
name: mon premier pipeline

on: 
    push:
        branches: [main]

jobs:
    # nom de votre premier job
    job1: 
        # sur quel type de machine votre job va s'exécuter
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello world!!"
        