#nom du pipeline
name: mon premier pipeline
on: 
    push:
        branches: [master]
    # ajouter un bouton pour déclencher le pipeline manuellement    
    workflow_dispatch:
jobs:
    # nom de votre premier job
    job1: 
        # sur quel type de machine votre job va s'exécuter
        runs-on: ubuntu-latest
        steps:
            - name: step 1
              run: echo "Hello world!!"
            - name: step 2
              # prendre le code sur git
              uses: actions/checkout@v6
            - name: step 3
              # afficher les fichier
              run: ls -a -l
            - name: step 4
              # installer .net
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: '8.0.x'
            - name: step 5
              run: dotnet restore
            - name: step 6
              run: dotnet build -o publish
            - name: step 7
              run: ls -a -l publish
        